
spring.datasource.url=jdbc:postgresql://localhost:5432/bookshelf
spring.datasource.username=bookshelf
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=ThisIsMySuperSecretKeyForJwt_AtLeast32CharsLong_DoNotShareIt
jwt.expiration=86400000

#logging.level.org.springframework.security=DEBUG